import {mkdir, writeFile} from "node:fs/promises";
import {resolve} from "node:path";
import {STORY_SCENES} from "../src/content.ts";

type Alignment = {
  characters: string[];
  character_start_times_seconds: number[];
  character_end_times_seconds: number[];
};

type ElevenLabsResponse = {
  audio_base64: string;
  alignment?: Alignment | null;
  normalized_alignment?: Alignment | null;
};

type Caption = {
  text: string;
  startMs: number;
  endMs: number;
  timestampMs: number | null;
  confidence: number | null;
};

const FPS = 30;
const VOICE_ID = process.env.ELEVENLABS_VOICE_ID ?? "cgSgspJ2msm6clMCkdW9";
const VOICE_NAME = process.env.ELEVENLABS_VOICE_NAME ?? "Jessica — Playful, Bright, Warm";
const apiKey = process.env.ELEVENLABS_API_KEY;

if (!apiKey) {
  throw new Error("ELEVENLABS_API_KEY is required. Load it into the process environment before running.");
}

const projectRoot = resolve(import.meta.dirname, "..");
const publicVoiceover = resolve(projectRoot, "public", "voiceover");
const generatedSource = resolve(projectRoot, "src", "generated");
await mkdir(publicVoiceover, {recursive: true});
await mkdir(generatedSource, {recursive: true});

const toCaptions = (alignment: Alignment): Caption[] => {
  const captions: Caption[] = [];
  let text = "";
  let start = 0;
  let end = 0;

  const flush = () => {
    if (!text.trim()) return;
    captions.push({
      text,
      startMs: Math.round(start * 1000),
      endMs: Math.max(Math.round(end * 1000), Math.round(start * 1000) + 40),
      timestampMs: Math.round(start * 1000),
      confidence: null,
    });
    text = "";
  };

  alignment.characters.forEach((character, index) => {
    const characterStart = alignment.character_start_times_seconds[index] ?? end;
    const characterEnd = alignment.character_end_times_seconds[index] ?? characterStart;
    if (text.length === 0) start = characterStart;
    text += character;
    end = characterEnd;
    if (/\s/.test(character)) flush();
  });
  flush();
  return captions;
};

const generated = [];
for (const scene of STORY_SCENES) {
  process.stdout.write(`Generating ${scene.id}… `);
  const response = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${VOICE_ID}/with-timestamps?output_format=mp3_44100_128`,
    {
      method: "POST",
      headers: {
        "xi-api-key": apiKey,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        text: scene.narration,
        model_id: "eleven_multilingual_v2",
        voice_settings: {
          stability: 0.5,
          similarity_boost: 0.78,
          style: 0.12,
          use_speaker_boost: true,
          speed: 1.04,
        },
      }),
    },
  );
  if (!response.ok) {
    const message = await response.text();
    throw new Error(`ElevenLabs failed for ${scene.id} (${response.status}): ${message.slice(0, 300)}`);
  }

  const payload = (await response.json()) as ElevenLabsResponse;
  const alignment = payload.normalized_alignment ?? payload.alignment;
  if (!alignment) throw new Error(`ElevenLabs returned no alignment for ${scene.id}`);

  const audioFile = `voiceover/${scene.id}.mp3`;
  await writeFile(resolve(projectRoot, "public", audioFile), Buffer.from(payload.audio_base64, "base64"));
  const captions = toCaptions(alignment);
  const audioSeconds = alignment.character_end_times_seconds.at(-1) ?? 0;
  const durationSeconds = Math.max(audioSeconds + 0.7, 2);
  const durationFrames = Math.ceil(durationSeconds * FPS);
  generated.push({
    id: scene.id,
    audioFile,
    audioSeconds: Number(audioSeconds.toFixed(3)),
    durationSeconds: Number(durationSeconds.toFixed(3)),
    durationFrames,
    captions,
  });
  process.stdout.write(`${audioSeconds.toFixed(1)}s\n`);
}

const manifest = {
  fps: FPS,
  voiceId: VOICE_ID,
  voiceName: VOICE_NAME,
  generatedAt: new Date().toISOString(),
  scenes: generated,
};

await writeFile(
  resolve(publicVoiceover, "manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);
await writeFile(
  resolve(generatedSource, "voiceover-manifest.ts"),
  `// Generated by scripts/generate-voiceover.ts.\nexport const VOICEOVER_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;\n`,
);

const totalSeconds = generated.reduce((sum, scene) => sum + scene.durationSeconds, 0);
console.log(`Generated ${generated.length} scenes with ${VOICE_NAME}. Total: ${totalSeconds.toFixed(1)}s.`);
